### ISSUE TITLE
Color compression fails when number of colors is an exact multiple of macro block size

### ISSUE THREAD

**Issue by mathijs727** [gegoggigog/DAG-example#1]
There is a bug in the color compression code by Dolonius (on the `Compression` branch).
When the code iterates over the macro blocks (called `parts` in the code) it incorrectly computes the size of the last macro block (line 838 of `ours_varbit.cpp`):
```c++
const size_t part_size =
        (part == nof_parts - 1) ?
        (n_colors % macro_block_size) : macro_block_size;
```

If the final part is exactly the size of a macro block then `n_colors % macro_block_size == 0` and those colors will be omitted from the result.
This can be easily fixed by replacing this expression by
```c++
const size_t part_size = std::min(n_colors - part * macro_block_size, macro_block_size);
```

**Comment by gegoggigog** [comment]
That was silly of me! Thanks!
